# Generated by Django 5.2 on 2025-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('lastename', models.CharField(max_length=20)),
                ('username', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('confirmpassword', models.TextField()),
            ],
        ),
    ]
