# Generated by Django 5.2 on 2025-09-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='lastename',
            new_name='lastname',
        ),
    ]
