# Generated by Django 5.2 on 2025-09-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_lastename_userinfo_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='mobile',
        ),
    ]
